month = input("Enter a month: ")
verb1 = input("Enter a verb: ")
place = input("Enter a place: ")
adj1 = input("Enter an adjective: ")
adj2 = input("Enter an adjective: ")
place2 = input("Enter a place: ")
verb2 = input("Enter a verb: ")
noun = input("Enter a noun: ")
verb3 = input("Enter a verb: ")
noun2 = input("Enter a noun: ")
adj3 = input("Enter an adjective: ")
adj4 = input("Enter a adjective: ")
color = input("Enter a color: ")
adj5 = input("Enter an adjective: ")
verb4 = input("Enter a verb: ")
verb5 = input("Enter a verb: ")
noun3 = input("Enter a noun: " )
exclamation = input("Enter an exclamation: ")
holiday = input("Enter a holiday: ")


print("Every " + month + " we " + verb1 + " to a tree " + place + " far away. Not just any " + adj1 + " farm, a " + adj2 + " tree " + place2 + ". My dad and I " + verb2 + " onto the " + noun + " to " + verb3 + " for the perfect " + noun2 + ".Some people like them " + adj3 + " and " + adj4 + " and some like them " + color + " and fat. We are searching for a tall and " + adj5 + " one! 'Over there!' I exclaim, 'Dad it's over there!' off we " +  verb4 + ", saw in hand to " + verb5 + " this year's " + noun3 + " down. " + exclamation + " it's " + holiday + " finally!") 
#This mad lib was sourced from woojr (https://woojr.com/wp-content/uploads/2016/11/christmas-ad-lib-tree.gif)
